-- Assistant RH IA CFDT : corpus documentaire, recherche vectorielle et historique.
-- Le modèle gte-small intégré aux Edge Functions Supabase produit 384 dimensions.

create extension if not exists vector with schema extensions;

create table if not exists public.rh_ai_documents (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  source_type text not null default 'accord',
  version text,
  effective_from date,
  effective_to date,
  file_path text,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rh_ai_chunks (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.rh_ai_documents(id) on delete cascade,
  chunk_index integer not null default 0,
  content text not null,
  page_number integer,
  article_ref text,
  embedding extensions.vector(384),
  created_at timestamptz not null default now(),
  unique(document_id, chunk_index)
);

create table if not exists public.rh_ai_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  question text not null,
  answer text not null,
  sources jsonb not null default '[]'::jsonb,
  provider text not null default 'gemini',
  model text,
  created_at timestamptz not null default now()
);

create index if not exists rh_ai_chunks_embedding_hnsw
  on public.rh_ai_chunks using hnsw (embedding extensions.vector_ip_ops);
create index if not exists rh_ai_chunks_document_idx on public.rh_ai_chunks(document_id);
create index if not exists rh_ai_messages_user_created_idx
  on public.rh_ai_messages(user_id, created_at desc);

alter table public.rh_ai_documents enable row level security;
alter table public.rh_ai_chunks enable row level security;
alter table public.rh_ai_messages enable row level security;

create or replace function public.current_user_is_adherent()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select u.is_adherent = true
    from public.users u
    where u.id = auth.uid()
    limit 1
  ), false);
$$;

revoke all on function public.current_user_is_adherent() from public;
grant execute on function public.current_user_is_adherent() to authenticated;

-- Les adhérents peuvent consulter uniquement leur propre historique.
drop policy if exists "rh_ai_messages_select_own_adherent" on public.rh_ai_messages;
create policy "rh_ai_messages_select_own_adherent"
on public.rh_ai_messages
for select
to authenticated
using (user_id = auth.uid() and public.current_user_is_adherent());

-- Aucune insertion directe depuis Flutter : l'Edge Function utilise service_role.
revoke insert, update, delete on public.rh_ai_messages from anon, authenticated;
revoke all on public.rh_ai_documents from anon, authenticated;
revoke all on public.rh_ai_chunks from anon, authenticated;

grant select on public.rh_ai_messages to authenticated;

create or replace function public.match_rh_ai_chunks(
  query_embedding extensions.vector(384),
  match_threshold float default 0.55,
  match_count integer default 6
)
returns table (
  chunk_id bigint,
  document_id uuid,
  title text,
  content text,
  page_number integer,
  article_ref text,
  similarity float
)
language sql
stable
security definer
set search_path = public, extensions
as $$
  select
    c.id as chunk_id,
    d.id as document_id,
    d.title,
    c.content,
    c.page_number,
    c.article_ref,
    (-(c.embedding <#> query_embedding))::float as similarity
  from public.rh_ai_chunks c
  join public.rh_ai_documents d on d.id = c.document_id
  where d.is_active = true
    and c.embedding is not null
    and (d.effective_from is null or d.effective_from <= current_date)
    and (d.effective_to is null or d.effective_to >= current_date)
    and -(c.embedding <#> query_embedding) >= match_threshold
  order by c.embedding <#> query_embedding
  limit greatest(1, least(match_count, 10));
$$;

revoke all on function public.match_rh_ai_chunks(extensions.vector, float, integer) from public;
grant execute on function public.match_rh_ai_chunks(extensions.vector, float, integer) to service_role;

comment on table public.rh_ai_documents is 'Documents validés servant de corpus à l’assistant RH IA.';
comment on table public.rh_ai_chunks is 'Extraits de documents et embeddings gte-small (384 dimensions).';
comment on table public.rh_ai_messages is 'Historique individuel des questions/réponses RH IA.';
