-- Module bandeau dynamique accueil CFDT
-- 2026-08-17

create extension if not exists pgcrypto;

create table if not exists public.home_banners (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 120),
  message text,
  style text not null default 'info'
    check (style in ('info', 'important', 'success')),
  icon_name text not null default 'campaign',
  action_type text not null default 'none'
    check (action_type in ('none', 'internal', 'url', 'pdf', 'news')),
  action_value text,
  action_label text,
  audiences text[] not null default array['all']::text[],
  platforms text[] not null default array['all']::text[],
  starts_at timestamptz,
  ends_at timestamptz,
  is_active boolean not null default false,
  is_dismissible boolean not null default true,
  sort_order integer not null default 100,
  image_storage_path text,
  archived_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint home_banners_dates_ok check (
    ends_at is null or starts_at is null or ends_at > starts_at
  ),
  constraint home_banners_action_ok check (
    action_type = 'none' or nullif(btrim(action_value), '') is not null
  )
);

create index if not exists home_banners_live_idx
  on public.home_banners (is_active, archived_at, sort_order, starts_at, ends_at);

create table if not exists public.home_banner_events (
  id bigint generated by default as identity primary key,
  banner_id uuid not null references public.home_banners(id) on delete cascade,
  event_type text not null check (event_type in ('impression', 'click', 'dismiss')),
  user_id uuid references auth.users(id) on delete set null default auth.uid(),
  session_id text not null check (char_length(session_id) between 8 and 120),
  platform text not null,
  created_at timestamptz not null default now()
);

create index if not exists home_banner_events_banner_created_idx
  on public.home_banner_events (banner_id, created_at desc);
create index if not exists home_banner_events_type_created_idx
  on public.home_banner_events (event_type, created_at desc);

create or replace function public.touch_home_banner_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  new.updated_by = auth.uid();
  return new;
end;
$$;

drop trigger if exists trg_home_banners_updated_at on public.home_banners;
create trigger trg_home_banners_updated_at
before update on public.home_banners
for each row execute function public.touch_home_banner_updated_at();

-- Adapte ici les niveaux si votre table public.users utilise d'autres valeurs.
-- Les valeurs connues de l'app sont adm / supuser ; admin / superadmin sont tolérées.
create or replace function public.is_home_banner_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    exists (
      select 1
      from public.users u
      where u.id = auth.uid()
        and lower(coalesce(u.level::text, ''))
          in ('adm', 'admin', 'supuser', 'superadmin')
    )
    or exists (
      select 1
      from public.users u
      join public.role_table r
        on r.matricule::text = u.matriculeaf::text
      where u.id = auth.uid()
        and lower(coalesce(r.role::text, ''))
          in ('adm', 'admin', 'supuser', 'superadmin')
    );
$$;

revoke all on function public.is_home_banner_admin() from public;
grant execute on function public.is_home_banner_admin() to authenticated;

alter table public.home_banners enable row level security;
alter table public.home_banner_events enable row level security;

-- Lecture publique : uniquement les bandeaux effectivement diffusables.
-- audiences/platforms restent un ciblage d'affichage, pas une frontière de sécurité.
drop policy if exists home_banners_public_read_live on public.home_banners;
create policy home_banners_public_read_live
on public.home_banners
for select
to anon, authenticated
using (
  is_active = true
  and archived_at is null
  and (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at > now())
);

-- Les administrateurs peuvent voir et gérer toutes les lignes.
drop policy if exists home_banners_admin_select on public.home_banners;
create policy home_banners_admin_select
on public.home_banners
for select
to authenticated
using (public.is_home_banner_admin());

drop policy if exists home_banners_admin_insert on public.home_banners;
create policy home_banners_admin_insert
on public.home_banners
for insert
to authenticated
with check (public.is_home_banner_admin());

drop policy if exists home_banners_admin_update on public.home_banners;
create policy home_banners_admin_update
on public.home_banners
for update
to authenticated
using (public.is_home_banner_admin())
with check (public.is_home_banner_admin());

drop policy if exists home_banners_admin_delete on public.home_banners;
create policy home_banners_admin_delete
on public.home_banners
for delete
to authenticated
using (public.is_home_banner_admin());

-- Analytics : insertion minimale, uniquement vers un bandeau actuellement lisible.
drop policy if exists home_banner_events_anon_insert on public.home_banner_events;
create policy home_banner_events_anon_insert
on public.home_banner_events
for insert
to anon
with check (
  user_id is null
  and exists (
    select 1 from public.home_banners b
    where b.id = banner_id
      and b.is_active = true
      and b.archived_at is null
      and (b.starts_at is null or b.starts_at <= now())
      and (b.ends_at is null or b.ends_at > now())
  )
);

drop policy if exists home_banner_events_auth_insert on public.home_banner_events;
create policy home_banner_events_auth_insert
on public.home_banner_events
for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.home_banners b
    where b.id = banner_id
      and b.is_active = true
      and b.archived_at is null
      and (b.starts_at is null or b.starts_at <= now())
      and (b.ends_at is null or b.ends_at > now())
  )
);

drop policy if exists home_banner_events_admin_read on public.home_banner_events;
create policy home_banner_events_admin_read
on public.home_banner_events
for select
to authenticated
using (public.is_home_banner_admin());

-- Bucket privé optionnel pour une illustration du bandeau.
insert into storage.buckets (id, name, public, file_size_limit)
values ('home-banners', 'home-banners', false, 5242880)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit;

-- Lecture des images seulement si elles sont rattachées à un bandeau diffusé.
drop policy if exists home_banners_storage_live_read on storage.objects;
create policy home_banners_storage_live_read
on storage.objects
for select
to anon, authenticated
using (
  bucket_id = 'home-banners'
  and exists (
    select 1 from public.home_banners b
    where b.image_storage_path = name
      and b.is_active = true
      and b.archived_at is null
      and (b.starts_at is null or b.starts_at <= now())
      and (b.ends_at is null or b.ends_at > now())
  )
);

-- CRUD storage réservé aux admins.
drop policy if exists home_banners_storage_admin_all on storage.objects;
create policy home_banners_storage_admin_all
on storage.objects
for all
to authenticated
using (bucket_id = 'home-banners' and public.is_home_banner_admin())
with check (bucket_id = 'home-banners' and public.is_home_banner_admin());

-- Petite fonction RPC d'analytics agrégées, réservée admin.
create or replace function public.home_banner_stats(p_banner_id uuid)
returns table (
  impressions bigint,
  clicks bigint,
  dismissals bigint,
  click_rate numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select
    count(*) filter (where e.event_type = 'impression') as impressions,
    count(*) filter (where e.event_type = 'click') as clicks,
    count(*) filter (where e.event_type = 'dismiss') as dismissals,
    case
      when count(*) filter (where e.event_type = 'impression') = 0 then 0::numeric
      else round(
        100.0 * count(*) filter (where e.event_type = 'click')
        / count(*) filter (where e.event_type = 'impression'),
        2
      )
    end as click_rate
  from public.home_banner_events e
  where e.banner_id = p_banner_id
    and public.is_home_banner_admin();
$$;

revoke all on function public.home_banner_stats(uuid) from public;
grant execute on function public.home_banner_stats(uuid) to authenticated;
